# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/loadingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingOverlay(object):
    def setupUi(self, LoadingOverlay):
        LoadingOverlay.setObjectName("LoadingOverlay")
        LoadingOverlay.resize(120, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoadingOverlay.sizePolicy().hasHeightForWidth())
        LoadingOverlay.setSizePolicy(sizePolicy)
        LoadingOverlay.setMinimumSize(QtCore.QSize(120, 120))
        LoadingOverlay.setMaximumSize(QtCore.QSize(120, 120))
        LoadingOverlay.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.hlayout_window = QtWidgets.QHBoxLayout(LoadingOverlay)
        self.hlayout_window.setContentsMargins(0, 0, 0, 0)
        self.hlayout_window.setObjectName("hlayout_window")
        self.lbl_image = QtWidgets.QLabel(LoadingOverlay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image.sizePolicy().hasHeightForWidth())
        self.lbl_image.setSizePolicy(sizePolicy)
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.hlayout_window.addWidget(self.lbl_image)

        self.retranslateUi(LoadingOverlay)
        QtCore.QMetaObject.connectSlotsByName(LoadingOverlay)

    def retranslateUi(self, LoadingOverlay):
        _translate = QtCore.QCoreApplication.translate
        LoadingOverlay.setWindowTitle(_translate("LoadingOverlay", "Загрузка..."))
