# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/GUI_preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviewWin(object):
    def setupUi(self, PreviewWin):
        PreviewWin.setObjectName("PreviewWin")
        PreviewWin.resize(922, 528)
        PreviewWin.setMinimumSize(QtCore.QSize(922, 528))
        PreviewWin.setMaximumSize(QtCore.QSize(922, 528))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PreviewWin)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_image = QtWidgets.QLabel(PreviewWin)
        self.lbl_image.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout.addWidget(self.lbl_image)

        self.retranslateUi(PreviewWin)
        QtCore.QMetaObject.connectSlotsByName(PreviewWin)

    def retranslateUi(self, PreviewWin):
        _translate = QtCore.QCoreApplication.translate
        PreviewWin.setWindowTitle(_translate("PreviewWin", "Рабочие зоны"))
