# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/previewGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviewWindow(object):
    def setupUi(self, PreviewWindow):
        PreviewWindow.setObjectName("PreviewWindow")
        PreviewWindow.resize(922, 528)
        PreviewWindow.setMinimumSize(QtCore.QSize(922, 528))
        PreviewWindow.setMaximumSize(QtCore.QSize(922, 528))
        self.hlayout_window = QtWidgets.QHBoxLayout(PreviewWindow)
        self.hlayout_window.setObjectName("hlayout_window")
        self.lbl_image = QtWidgets.QLabel(PreviewWindow)
        self.lbl_image.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.hlayout_window.addWidget(self.lbl_image)

        self.retranslateUi(PreviewWindow)
        QtCore.QMetaObject.connectSlotsByName(PreviewWindow)

    def retranslateUi(self, PreviewWindow):
        _translate = QtCore.QCoreApplication.translate
        PreviewWindow.setWindowTitle(_translate("PreviewWindow", "Рабочие зоны"))
